name: Test suite

on:
    push:
        branches:
            - dev
    pull_request:
        branches:
            - dev

jobs:
    clippy_check:
        name: Clippy
        runs-on: ubuntu-latest
        steps:
            - run: sudo apt-get install -y libssl-dev
            - uses: actions/checkout@v2
            - uses: actions-rs/toolchain@v1
              with:
                  toolchain: nightly
                  components: clippy
                  override: true
            - uses: actions-rs/clippy-check@v1
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  args: --all-features
    test:
        name: Test suite
        runs-on: ubuntu-latest
        steps:
            - run: sudo apt-get install -y libssl-dev
            - uses: actions/checkout@v2
            - uses: actions/cache@v1
              env:
                  cache-name: cache-target
              with:
                  path: target
                  key: ${{ runner.os }}-${{ env.cache-name }}
                  restore-keys: |
                      ${{ runner.os }}
            - run: |
                rustup update
                cargo fmt --all -- --check
                cargo build
                cargo test
